name: "KTH DevOps course content verificator"
description: "Verifies that contents are changed in correct location and that markdown file contains the necassary info structure"
author: "Ralfs Zangis"
inputs:
  location:
    description: "Regex path showcasing expected file location"
    required: true
  changes:
    description: "Space separated location of changes"
    required: true
  structure:
    description: "Expected file content structure"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"